#!/bin/env sh

# Author: Kelves C.
# Version: 0.9.6
# License: Public Domain
# Description:
# Wrap up script to start a set of programs when X starts

kblayer 2> $(mktemp -t kblayer.log.XXX) &
xrdb $HOME/.Xresources 2> $(mktemp -t xrdb.log.XXX) &

[ $(pidof -xs urxvtd) ] || urxvtd -q -o -f &

[ $(pidof -xs xbanish) ] || setsid xbanish &

setsid xsetroot -cursor_name left_ptr &

randomize-bg 2>&1 1> $(mktemp -t wall.log.XXX) &

picom --config=$XDG_CONFIG_HOME/compton/compton.conf \
    2> $(mktemp -t compton.log.XXX) &
picomPID=$!

while ! ps -hp $picomPID > /dev/null;do
    sleep 1
done

bar 2>&1 1> $(mktemp -t bar.log.XXX) &
[ $(pidof -xs usblistener.sh) ] || usblistener.sh &
[ $(pidof -xs conky) ] || conky 2>&1 1> $(mktemp -t conky.log.XXX) &

unset $Pid_of_Compton
