#!/bin/env sh

# Author: Kelves C.
# Version: 0.9.3
# License: Public Domain
# Description:
# Wrap up script to start all programs that compose the work evironment 
# when the xsession starts
# TODO: reorganize the commands

kblayer 2> $(mktemp -t kblayer.log.XXX) &
xrdb $HOME/.Xresources 2> $(mktemp -t xrdb.log.XXX) &

[ $(pidof -xs xbanish) ] || setsid xbanish &

[ $(pidof -xs xsetroot) ] || setsid xsetroot -cursor_name left_ptr &

[ $(pidof -xs urxvtd) ] || urxvtd -q -o -f &

([ $(pidof -xs ranmoize-bg)] && kill $(pidof -xs ramdomize-bg)) || randomize-bg \
    2> $(mktemp -t wall.log.XXX) &

picom --config=$XDG_CONFIG_HOME/compton/compton.conf \
    2> $(mktemp -t compton.log.XXX) &
picomPID=$!

while ! ps -hp $picomPID > /dev/null;do
    sleep 1
done
conky > /dev/null &
bar 2>&1 1> $(mktemp -t bar.log.XXX) &

unset $Pid_of_Compton
