#!/usr/bin/env sh

# TODO:
#   help message
#   change this to a multi option script

# In [:print:] includes:
#   [:alnum:] : alpha-numerics
#   [:punct:] : punctuations
#   spaces
# \t can be replaced by [:blank:]

# To delete empity lines in the file:
#   sed '/^[[:space:]]*$/d'
#   sed '/^$/d'
#   sed '/^[ \t]*$/d'
#   awk 'NF'
#   awk /./

# To update the file:
#   sed -i

# Many other good examples can be found in stackoverflow

#tr -dC '[:print:]\t\n' \
#    | sed '/^$/d'
tr -C '[:print:]\t\n' '\n' \
    | sed '/^$/d'

