#!/usr/bin/sh

# Author: Kelves Costa
# License: Public Domain
# Version: 0.5-alpha
# Description: Simple script to realod sxhkd new configuration

# lookup for sxhkd and exits if false
pgrep -i sxhkd 2>&1 1> /dev/null || exit 1 
# kill all running sxhkd instances
kill $(pidof sxhkd)
# executes a new single instance of the deamon
exec setsid sxhkd -c "$XDG_CONFIG_HOME/sxhkd/sxhkdrc" \
    > $(mktemp -q -t sxhkd.XXX) &  
# sucess exit status returned
exit 0  
