#!/usr/bin/env sh

# Sets the base keyborad layout to br-abnt2
setxkbmap br -variant abnt2
# To remap a key xmodmap -e "keycode <number> = <key>
# Where <number> is the key's number and <key> is the new value
xmodmap -e "keycode 66 = Escape"
xmodmap -e "clear lock"
xmodmap -e "keycode 108 = Alt_L"
xmodmap -e "keycode 34 = bar"

# xset r enables the new values to repete even when key is kept pressed
xset r 66
xset r 108
xset r 34
