#!/usr/bin/env sh

# QED: quick edit for the main config file
# Version: 0.1

case $1 in
    vi)        file=$HOME/.config/nvim/init.vim ;;
    wm)      file=$HOME/.config/bspwm/bspwmrc ;;
    hk)      file=$HOME/.config/sxhkd/sxhkdrc ;;
    sh)       file=$HOME/.mkshrc ;;
    *)          exit 1 ;;
esac

exec sakura --colorset 1 -x "nvim "$file"" 2> /dev/null &
