#!/bin/sh

# Author: Kelves C.
# Version: 0.9.0-beta
# License: Public Domain
# Description:
# Sets a background and then randomizes a new one after a couple minutes.

# Wallpapers directory
wallDir=/usr/share/wallpapers

# These signal must be sent to the pid of sleep, not randomize-bg
trap 'set_background' 10
trap 'set_background' 12

# Set the wallpaper filling the screen and without a ".fehbg" file
set_background() {
  wallpaper=$(ls -A $wallDir | shuf | sed 1q)
  feh --no-fehbg --bg-scale $wallDir/$wallpaper
}

while true;do
    set_background
    sleep 240
done

