#!/bin/bash

# Author: Kelves C.
# Version: 0.6.0-beta (usable)
# License: Public Domain
# Description: 
# Search through the subtree of a directory where pdfs are stored
# and open the selected file in zathura

LIBRARIES=(/archv/papers)

while true;do
  PAPER=$(find ${LIBRARIES[@]} -type f -name *.pdf | fzy) 
  if [ -f "$PAPER" ];then
    # Initializes the pdfreader program
  	zathura "$PAPER" &
    break
  elif [ ! -e "$PAPER" ];then
  	    exit 1
  else
  targetDir="$PAPER"
fi
done
exit
