#!/usr/bin/mksh

#Author: Kelves C.
#License: Public Domain
#Version: 0.5.2-beta
#Description: shows system shutdown options and executed the selected one

if ! pidof -xs startx 2>&1 1> /dev/null; then
    options="Poweroff\nHalt\nSuspend\nHibernate\nReboot\n"
    if which fzy > /dev/null; then
        action=$(echo -en "$options" | fzy)
        case $action in
            Poweroff);;
            Suspend);;
            *);;
        esac
    fi
fi

rofi_cmd="rofi -theme pmenu"

POWEROFF=$(echo -e "\UF011")    # poweroff button
SUSPEND=$(echo -e "\UF186")     # moon button
HIBERNATE=$(echo -e "\UF0C8")   # square button
REBOOT=$(echo -e "\UF2EA")      # reboot button

# rofi dmenu options explained:
# -p is for the prompt, the default is "dmenu"
# -i is for case insensitive
# -u is for the nth column be urgent

action="$(printf "%s\\n%s\\n%s\\n%s" $POWEROFF $SUSPEND $HIBERNATE $REBOOT | \
    $rofi_cmd -lines 1 -width 60 -columns 4 -dmenu -i -u 0 -p "Shut")"

case "$action" in
    $POWEROFF)
        sudo poweroff;;
    $SUSPEND)
        sudo zzz;;
    $HIBERNATE)
        sudo ZZZ;;
    $REBOOT)
        sudo reboot;;
    *)
        break;;
esac

